In [2]:
import numpy as np

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [46]:
np.dot(a[0],c[0])

14

In [12]:
b=np.array([[11,21,31],[14,15,16],[17,28,19]])

In [47]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
d=np.array([1,2,3])
e=np.array([1,2,3,4,5,6])

In [57]:
d[:,np.newaxis]+e[np.newaxis,:]

array([[2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [73]:
d.reshape(-1,1)+e.reshape(1,-1)

array([[2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [77]:
d.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [75]:
d.reshape(1,-1)

array([[1, 2, 3]])

In [68]:
e.reshape(1,-1).shape

(1, 6)

In [63]:
d.reshape(-1,1)+e.reshape(1,-1)

array([[2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [23]:
2*(np.sum(a*b))

1774

In [43]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.dot(a,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [44]:
a*c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [40]:
x[:,np.newaxis].shape

(3, 1)

In [37]:
x.shape

(3,)

In [8]:
np.sum(b)

172

In [101]:
mul1=np.array([[1,2,3],[1,2,3]])
mul2=np.array([[1,1,1],[2,2,2],[3,3,3]])

In [103]:
np.dot(mul1,mul2)

array([[14, 14, 14],
       [14, 14, 14]])

In [98]:
mul1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [123]:
ar1=np.random.randn(8).reshape(4,2)

In [124]:
ar2=np.random.randn(8).reshape(4,2)

In [125]:
ar3=np.random.randn(8).reshape(4,2)

In [127]:
arrayFarray=[ar1,ar2,ar3]

In [153]:
newarrayFarray=[arrayFarray[i] for i in [0,2]]

In [167]:
np.array(newarrayFarray).reshape(8,2)

array([[-1.62246443, -0.52707816],
       [-0.32769592, -1.53218376],
       [-0.96663182,  1.4578982 ],
       [-0.71944206,  0.57116083],
       [ 0.9770084 , -0.55295748],
       [ 0.65429364, -1.56536021],
       [-0.55473183, -0.8044593 ],
       [-0.51545293,  0.65934384]])

In [165]:
newarrayFarray[0].shape

(4, 2)

In [121]:
[i for i in ar if i!=3]


[0, 1, 2, 4]

In [108]:
k_choices = [1, 3, 5, 8, 10, 12, 15, 20, 50, 100]

In [173]:
acc

[1, 2]

In [190]:
row=np.array([1,2,3,4]).reshape(1,4)
col=np.array([1,2,3,4]).reshape(4,1)

In [193]:
row

array([[1, 2, 3, 4]])

In [194]:
col

array([[1],
       [2],
       [3],
       [4]])

In [196]:
np.nditer

numpy.nditer